name: mister-anderson
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pytest
  - pip
  - isort
  - setuptools
  - openai
  - nose
  - flask
  - jaydebeapi
  - pandas
  - yaml
  - pyyaml
  - fastapi
  - pyodbc
prefix: /Users/gui/miniforge3/envs/mister-anderson
